#!/usr/bin/env perl
# dmft_init - prepare a new DMFT run (called from dmft_monitor)
# Rok Zitko, 2008-2025

if (!-d "dmft") {
  mkdir "dmft" or die "Can't create subdir dmft, stopped";
}

if (!-d "res") {
    mkdir "res" or die "Cant create subdit res, stopped";
}

if (-e "DeltaFirst.dat" && !-e "mesh.dat") {
    system "cp DeltaFirst.dat mesh.dat";
}

if (!-e "DeltaFirst.dat") {
    if (!-e "mesh.dat") {
      system "./init_mesh >mesh.dat";
    }
    system "./init_Sigma";
    system "./bandDOS";
    system "scaley -1 ImDelta.dat >DeltaFirst.dat";
}

-e "Delta.dat" or system "cp DeltaFirst.dat Delta.dat";
